version: 1.1.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages

skip_tags: false

skip_commits:
  files:
    - '**/*.md'

image: Visual Studio 2017

clone_folder: C:\Sugoi-Player

shallow_clone: true

matrix:
  fast_finish: true
  allow_failures:
    - platform: x64
      configuration: Release
  exclude:
    - platform: x86
    - configuration: Debug

platform: x64

configuration: Release

before_build:
  - CALL "C:\Qt\5.10.0\msvc2017_64\bin\qtenv2.bat"
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - SET "PATH=%APPVEYOR_BUILD_FOLDER%\3rdparty\jom;%PATH%"
  - CD /D "%APPVEYOR_BUILD_FOLDER%"
  - IF EXIST bin64 RD /S /Q bin64

build_script:
  - CALL update_version.bat
  - qmake "sugoi-player.pro" -spec win32-msvc "CONFIG+=release"
  - jom qmake_all
  - jom && jom install
  - jom distclean
  - IF EXIST bin64 RD /S /Q bin64

on_failure:
  - jom distclean
  - IF EXIST "%APPVEYOR_BUILD_FOLDER%\bin64" RD /S /Q "%APPVEYOR_BUILD_FOLDER%\bin64"

test: off

artifacts:
  - path: ci_version.h

deploy: off

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
